import * as fs from 'fs-extra';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';

export async function setupSystemLevelMonitoring(easyaiDir: string): Promise<void> {
  console.log(chalk.blue('\n🔧 Setting up system-level monitoring...'));
  
  // Create universal wrapper commands
  await createUniversalWrappers(easyaiDir);
  
  // Create shell profile modifications
  await createShellProfileAdditions(easyaiDir);
  
  // Auto-apply to current shell profiles
  await applyToShellProfiles(easyaiDir);
  
  console.log(chalk.green('✅ System-level monitoring configured!'));
}

async function createUniversalWrappers(easyaiDir: string): Promise<void> {
  const wrappersDir = path.join(easyaiDir, 'wrappers');
  await fs.ensureDir(wrappersDir);
  
  // Python wrapper with auto-import
  const pythonWrapper = `#!/bin/bash
# EasyAI Python Wrapper - Auto-imports monitoring
export PYTHONPATH="${easyaiDir}:\$PYTHONPATH"
python3 -c "
import sys
sys.path.insert(0, '${easyaiDir}')
try:
    import easyai_interceptor
    print('[EasyAI] Python monitoring active', file=sys.stderr)
except:
    pass
exec(open(sys.argv[1]).read())
" "$@"
`;

  // Node.js wrapper with auto-require
  const nodeWrapper = `#!/bin/bash
# EasyAI Node.js Wrapper - Auto-requires monitoring
NODE_OPTIONS="-r ${easyaiDir}/node-preload.js" node "$@"
`;

  // Go wrapper with proxy
  const goWrapper = `#!/bin/bash
# EasyAI Go Wrapper - Uses proxy for monitoring
export HTTP_PROXY=http://127.0.0.1:8888
export HTTPS_PROXY=http://127.0.0.1:8888
source "${easyaiDir}/config/easyai.env" 2>/dev/null
go "$@"
`;

  // Curl wrapper with proxy
  const curlWrapper = `#!/bin/bash
# EasyAI Curl Wrapper - Uses proxy for monitoring
export HTTP_PROXY=http://127.0.0.1:8888
export HTTPS_PROXY=http://127.0.0.1:8888
source "${easyaiDir}/config/easyai.env" 2>/dev/null
curl "$@"
`;

  // Universal language detector and wrapper
  const universalWrapper = `#!/bin/bash
# EasyAI Universal Wrapper - Detects language and applies appropriate monitoring

FILE="\$1"
COMMAND="\$1"

# Source EasyAI environment
source "${easyaiDir}/config/easyai.env" 2>/dev/null

# Language detection and wrapper selection
if [[ "\$FILE" == *.py ]] || [[ "\$COMMAND" == "python"* ]]; then
    # Python: Use interceptor
    export PYTHONPATH="${easyaiDir}:\$PYTHONPATH"
    python3 -c "
import sys
sys.path.insert(0, '${easyaiDir}')
try:
    import easyai_interceptor
    print('[EasyAI] Python monitoring active', file=sys.stderr)
except:
    pass
exec(open(sys.argv[1]).read())
" "\${@:2}"
    
elif [[ "\$FILE" == *.js ]] || [[ "\$FILE" == *.ts ]] || [[ "\$COMMAND" == "node"* ]]; then
    # Node.js: Use preload
    NODE_OPTIONS="-r ${easyaiDir}/node-preload.js" node "\${@:2}"
    
elif [[ "\$COMMAND" == "curl"* ]]; then
    # Curl: Use proxy
    export HTTP_PROXY=http://127.0.0.1:8888
    export HTTPS_PROXY=http://127.0.0.1:8888
    curl "\${@:2}"
    
elif [[ "\$COMMAND" == "go"* ]]; then
    # Go: Use proxy
    export HTTP_PROXY=http://127.0.0.1:8888
    export HTTPS_PROXY=http://127.0.0.1:8888
    go "\${@:2}"
    
else
    # Unknown: Use proxy
    export HTTP_PROXY=http://127.0.0.1:8888
    export HTTPS_PROXY=http://127.0.0.1:8888
    "\$@"
fi
`;

  // Write all wrappers
  const wrappers = {
    'easyai-python': pythonWrapper,
    'easyai-node': nodeWrapper, 
    'easyai-go': goWrapper,
    'easyai-curl': curlWrapper,
    'easyai-run': universalWrapper
  };

  for (const [name, content] of Object.entries(wrappers)) {
    const wrapperPath = path.join(wrappersDir, name);
    await fs.writeFile(wrapperPath, content);
    await fs.chmod(wrapperPath, 0o755);
  }

  console.log(chalk.green('✅ Universal wrapper commands created'));
}

async function createShellProfileAdditions(easyaiDir: string): Promise<void> {
  const shellConfig = `
# EasyAI Universal Monitoring - Auto-generated by EasyAI CLI
# This section enables automatic API monitoring for all languages

# Add EasyAI wrappers to PATH
export PATH="${easyaiDir}/wrappers:\$PATH"

# EasyAI environment variables
source "${easyaiDir}/config/easyai.env" 2>/dev/null

# Universal monitoring aliases
alias python3='${easyaiDir}/wrappers/easyai-python'
alias python='${easyaiDir}/wrappers/easyai-python'
alias node='${easyaiDir}/wrappers/easyai-node'
alias go='HTTP_PROXY=http://127.0.0.1:8888 HTTPS_PROXY=http://127.0.0.1:8888 go'
alias curl='HTTP_PROXY=http://127.0.0.1:8888 HTTPS_PROXY=http://127.0.0.1:8888 curl'

# Universal run command
alias run='${easyaiDir}/wrappers/easyai-run'

# EasyAI status indicator
echo "🚀 EasyAI monitoring active for this shell session"
echo "   python, node, go, curl commands are automatically monitored"
echo "   Use 'easyai ui' to view captured requests"
`;

  const shellConfigPath = path.join(easyaiDir, 'shell-config.sh');
  await fs.writeFile(shellConfigPath, shellConfig);
  
  console.log(chalk.green('✅ Shell configuration created'));
}

async function applyToShellProfiles(easyaiDir: string): Promise<void> {
  const homeDir = os.homedir();
  const shellConfigPath = path.join(easyaiDir, 'shell-config.sh');
  
  const shellProfiles = [
    path.join(homeDir, '.bashrc'),
    path.join(homeDir, '.zshrc'),
    path.join(homeDir, '.bash_profile'),
    path.join(homeDir, '.profile')
  ];

  const sourceCommand = `
# EasyAI Universal Monitoring (added by EasyAI CLI)
if [ -f "${shellConfigPath}" ]; then
    source "${shellConfigPath}"
fi
`;

  let appliedCount = 0;

  for (const profilePath of shellProfiles) {
    try {
      if (await fs.pathExists(profilePath)) {
        const content = await fs.readFile(profilePath, 'utf8');
        
        // Check if already added
        if (!content.includes('EasyAI Universal Monitoring')) {
          await fs.appendFile(profilePath, sourceCommand);
          appliedCount++;
          console.log(chalk.gray(`   Added to ${path.basename(profilePath)}`));
        }
      }
    } catch (error) {
      // Ignore permission errors
    }
  }

  if (appliedCount > 0) {
    console.log(chalk.green(`✅ Applied to ${appliedCount} shell profile(s)`));
    console.log(chalk.yellow('💡 Restart your terminal or run: source ~/.bashrc'));
  } else {
    console.log(chalk.yellow('💡 Manual setup: Add this to your shell profile:'));
    console.log(chalk.cyan(`   source "${shellConfigPath}"`));
  }
}

export async function createPythonPackage(easyaiDir: string): Promise<void> {
  // Create proper Python package structure
  const packageDir = path.join(easyaiDir, 'easyai');
  await fs.ensureDir(packageDir);

  // __init__.py - Auto-loads interceptor
  const initPy = `"""
EasyAI Python Package
Automatically enables API request monitoring when imported.
"""
import os
import sys

# Add current directory to path
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

# Auto-load interceptor
try:
    from . import interceptor
    print("[EasyAI] Monitoring enabled", file=sys.stderr)
except ImportError:
    try:
        import easyai_interceptor
        print("[EasyAI] Monitoring enabled", file=sys.stderr)
    except ImportError:
        pass

__version__ = "1.0.0"
__all__ = ["interceptor"]
`;

  // setup.py for local installation
  const setupPy = `from setuptools import setup, find_packages

setup(
    name="easyai",
    version="1.0.0",
    description="EasyAI API monitoring package",
    packages=find_packages(),
    python_requires=">=3.6",
    install_requires=[
        "requests",
    ],
)
`;

  await fs.writeFile(path.join(packageDir, '__init__.py'), initPy);
  await fs.writeFile(path.join(easyaiDir, 'setup.py'), setupPy);
  
  // Copy interceptor as module
  const interceptorSource = path.join(__dirname, '..', '..', 'scripts', 'python', 'easyai_interceptor.py');
  const interceptorDest = path.join(packageDir, 'interceptor.py');
  
  try {
    await fs.copy(interceptorSource, interceptorDest);
  } catch (error) {
    console.warn(chalk.yellow('⚠️  Could not copy Python interceptor'));
  }

  console.log(chalk.green('✅ Python package structure created'));
  console.log(chalk.cyan('💡 Users can now use: import easyai'));
}